### ISSUE TITLE
Implement missing triggers

### ISSUE THREAD

**Issue by SGOrava** [SGOrava/radix-map-editor#14]
Currently there are more triggers in the spec than there are triggers implemented.
- [x] Teleport Trigger
- [x] Destination
- [x] Screen trigger
- [x] Checkpoint trigger
- [x] Remove trigger

Specification: https://github.com/GlPortal/specification/blob/master/formats/map/triggers.md#screen

**Comment by SGOrava** [comment]
@Geertiebear Hello, since you requested support for these trigger...
Work in progress can be found at branch [14-implement-missing-triggers ](https://github.com/SGOrava/radix-map-editor/tree/14-implement-missing-triggers)
Some work needs to be done in background before other things can be added....

**Comment by SGOrava** [comment]
Still needs some refactoring and testing but it is working right now.

**Comment by Geertiebear** [comment]
Super cool! Good work, maybe merge it with glPortal version?

**Comment by SGOrava** [comment]
Code should be the same, patch should work, well, if someone will do it.
But as you can see, i am not able to do it.
I plan to make things more readable and easier for me to work on, so expect the code to be less and less like my previous project (GlPortal "team" version).
